/** Canonical staging Render admin routes (from OpenAPI). Used by smoke tests. */
export const STAGING_BACKEND_ADMIN_ROUTES = [
  { method: "GET", path: "/api/v1/admin/dashboard", label: "dashboard" },
  { method: "GET", path: "/api/v1/admin/appointments", label: "appointments" },
  { method: "GET", path: "/api/v1/admin/doctors", label: "doctors" },
  { method: "GET", path: "/api/v1/admin/doctors/{id}/services", label: "doctor-services" },
  { method: "GET", path: "/api/v1/admin/doctor-categories", label: "doctor-categories" },
  { method: "GET", path: "/api/v1/admin/hospitals", label: "hospitals" },
  { method: "GET", path: "/api/v1/admin/users", label: "users" },
  { method: "GET", path: "/api/v1/admin/documents", label: "documents" },
  { method: "POST", path: "/api/v1/admin/documents", label: "documents-create" },
  { method: "GET", path: "/api/v1/admin/membership", label: "membership" },
  { method: "GET", path: "/api/v1/admin/payout-requests", label: "payout-requests" },
  { method: "GET", path: "/api/v1/admin/wallet-transactions", label: "wallet-transactions" },
  { method: "GET", path: "/api/v1/admin/admins", label: "admins" },
  { method: "GET", path: "/api/v1/admin/activity-logs", label: "activity-logs" },
  { method: "GET", path: "/api/v1/admin/activity/admin", label: "activity-admin" },
  { method: "GET", path: "/api/v1/admin/activity/platform", label: "activity-platform" },
  { method: "GET", path: "/api/v1/admin/legal-documents", label: "legal-documents" },
  { method: "PUT", path: "/api/v1/admin/legal-documents", label: "legal-documents-put" },
  { method: "PATCH", path: "/api/v1/admin/legal-documents", label: "legal-documents-patch" },
  { method: "GET", path: "/api/v1/admin/pregnancy-weeks", label: "pregnancy-weeks" },
  { method: "GET", path: "/api/v1/admin/child-growth-periods", label: "child-growth-periods" },
  { method: "GET", path: "/api/v1/admin/followup-templates", label: "followup-templates" },
  { method: "GET", path: "/api/v1/admin/daily-tips", label: "daily-tips" },
  { method: "GET", path: "/api/v1/admin/settings/finance", label: "settings-finance" },
  { method: "PUT", path: "/api/v1/admin/settings/finance", label: "settings-finance-put" },
  { method: "GET", path: "/api/v1/admin/settings/payment", label: "settings-payment" },
  { method: "PUT", path: "/api/v1/admin/settings/payment", label: "settings-payment-put" },
  { method: "GET", path: "/api/v1/admin/settings/subscription", label: "settings-subscription" },
  { method: "PUT", path: "/api/v1/admin/settings/subscription", label: "settings-subscription-put" },
  { method: "GET", path: "/api/v1/admin/settings/referral", label: "settings-referral" },
  { method: "PUT", path: "/api/v1/admin/settings/referral", label: "settings-referral-put" },
  { method: "GET", path: "/api/v1/admin/settings/app_version", label: "settings-app-version" },
  { method: "PUT", path: "/api/v1/admin/settings/app_version", label: "settings-app-version-put" },
  {
    method: "GET",
    path: "/api/v1/admin/settings/app_version_doctors",
    label: "settings-app-version-doctors",
  },
  {
    method: "PUT",
    path: "/api/v1/admin/settings/app_version_doctors",
    label: "settings-app-version-doctors-put",
  },
  { method: "GET", path: "/api/v1/admin/referrals", label: "referrals" },
  { method: "GET", path: "/api/v1/admin/referral-commissions", label: "referral-commissions" },
  { method: "GET", path: "/api/v1/admin/doctors/{id}/wallet", label: "doctor-wallet" },
  { method: "POST", path: "/api/v1/admin/doctors/{id}/verify", label: "doctor-verify" },
  { method: "GET", path: "/api/v1/admin/children", label: "children" },
  { method: "GET", path: "/api/v1/admin/children/{id}", label: "children-detail" },
  { method: "GET", path: "/api/v1/admin/appointments/{id}", label: "appointment-detail" },
  { method: "GET", path: "/api/v1/auth/session", label: "auth-session" },
  { method: "GET", path: "/api/v1/auth/me", label: "auth-me" },
] as const;

export type StagingBackendAdminRoute = (typeof STAGING_BACKEND_ADMIN_ROUTES)[number];
